kind: Service
apiVersion: v1
metadata:
  name: adams-service
  namespace: adams
spec:
  selector:
    app: adams-service
  type: LoadBalancer
  ports:
  - name: http-frontend
    port: 80
    targetPort: 80
  - name: http-userservice
    port: 5001
    targetPort: 5001
  - name: http-licenseservice
    port: 5002
    targetPort: 5002
  - name: http-datapoolservice
    port: 5003
    targetPort: 5003
  - name: http-notifyservice
    port: 5004
    targetPort: 5004
  - name: http-storageservice
    port: 5005
    targetPort: 5005
  - name: inferenceservice
    port: 5006
    targetPort: 5006
  - name: http-trainservice
    port: 5007
    targetPort: 5007
  - name: http-testservice
    port: 5008
    targetPort: 5008
  - name: http-pretrainedmodelservice
    port: 5009
    targetPort: 5009
  - name: http-datasetservice
    port: 5010
    targetPort: 5010
  - name: imageitemservice
    port: 5011
    targetPort: 5011
  
  
  
  # - name: noticeservice
  #   port: 5009
  #   targetPort: 5009
  
  
  # - name: continuoustrainingservice
  #   port: 5012
  #   targetPort: 5012
  # - name: workermanagementservice
  #   port: 5013
  #   targetPort: 5013